---
- name: Launch application
  community.docker.docker_container:
    name: backend
    image: "{{ dockerhub_username }}/tp-devops-simple-api:latest"
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/db"
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
    state: started
    recreate: true
    pull: true
